[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_BUILD_ID = "netlify-build-{timestamp}"

# ------------------------------------------
# REDIRECTIONS
# ------------------------------------------
[[redirects]]
  from = "/"
  to = "/Maintenance/VersionUpdater.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/src/pages/Products.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/src/pages/Contact.html"
  status = 200

[[redirects]]
  from = "/trust"
  to = "/src/pages/TrustSafetyPage.html"
  status = 200

[[redirects]]
  from = "/cart"
  to = "/src/pages/Cart.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/src/pages/Checkout.html"
  status = 200

[[redirects]]
  from = "/confirmation"
  to = "/src/pages/Confirmation.html"
  status = 200

# ------------------------------------------
# HEADERS
# ------------------------------------------
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/Crypted/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/src/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/src/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    X-Download-Options = "noopen"
    X-Permitted-Cross-Domain-Policies = "none"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https://images.unsplash.com https://*.netlify.app; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'"

# ------------------------------------------
# CUSTOM 404
# ------------------------------------------
[[redirects]]
  from = "/404"
  to = "/src/pages/404.html"
  status = 404
